### ISSUE TITLE
Blank page instead of redirect

### ISSUE THREAD

**Issue by hilburger** [1Conan/404-redirect-YOURLS#2]
Hi, 

I installed the plugin and added this line 
`define( 'CON_404_PAGE', 'http://www.law-school.de' );`
because I wanted 

1. to redirect all not found short links 
2. and those called with only the URL of the yourls system (without anything behind the domain like http://my-shortener.com). 

But in case 1 I get a blank page and the Chrome says: 
Failed to load resource: the server responded with a status of 404 (Not Found)

And in case 2 I get the access denied from the web server as listing is denied. 

Can you help me? 

Thanks and best regards, 
Thomas

**Comment by 1Conan** [comment]
Can you provide the domain that you setup your shortener to? (So I can test)
Give me a link of an invalid shortened link so I could see.

Have you checked php logs?
Does shortened links work? (Valid ones)

**Comment by 1Conan** [comment]
I forgot to say, that you can only set a local file to be the 404 file. 

This issue will be closed in 1 month
