### ISSUE TITLE
Server crash if _ is enabled

### ISSUE THREAD

**Issue by DatDraggy** [1Conan/404-redirect-YOURLS#3]
Hey there.
I like this plugin but I'd like to be able to use _ in urls so I made a little plugin myself. https://github.com/DatDraggy/underscores-in-url

When you have both plugins enabled and enter an unknown yourls url, more and more apache processes pop up until the server dies!
This happens with any kind of url. sho.rt/swag and sho.rt/sw_ag

The same thing happens when you just add an underscore to the charset in functions.php
No error in my logs though.
Any ideas?

https://puu.sh/udeK1/91371d81a5.png

https://puu.sh/udeMH/e879c4325e.png

**Comment by DatDraggy** [comment]
Okay so apparently that's why my https://github.com/DatDraggy/anti-youtube-preview isn't working either. Thats so strange...

**Comment by 1Conan** [comment]
I honestly don't know any reason why it won't work with this plugin.

Does the url exist? Tried your plugin with vanilla YOURLS?

**Comment by DatDraggy** [comment]
For example, sho.rt/notexist doesnt exist in the database. When you have the 404-redirect and the underscore plugin active/underscore in charset and try to go to sho.rt/notexist, it will load indefinitely and it'll spawn more and more apache servers until it reaches the limit and crashes.
However if the URL exists, everything works fine. Even with _ in the shortened URL.

Yes. I tried a fresh install, cleared cache and tried to replicate. It just brings me to the root domain like it should when only my plugin is activated and I enter an invalid url. When I put your plugin in there and activate it too, the problem occurs again. When I remove mine, the 404 header is being sent.

That's really strange...

**Comment by 1Conan** [comment]
What are the response headers when the problem occurs?

**Comment by DatDraggy** [comment]
None because the page just doesn't load until apache says "Fuck it. I'm not doing this anymore". https://puu.sh/uhNTM/0f27c52a2b.png
Screenshot of the processes on my test server when I enter an invalid url: https://puu.sh/uhNNR/e59642da66.png

**Comment by 1Conan** [comment]
Sorry for the late reply. Totally forgot about this.

I believe this is a problem with YOURLS though.

**Comment by DatDraggy** [comment]
Lol no worries xP

Hmhmm that's the only thing I can think of as well. Really strange. I'll just leave it inside my code then and just add a little "incompatible with blabla" notice on my plugin.

**Comment by 1Conan** [comment]
Okay :)
